import React, { createContext, useContext, useState, useCallback } from 'react';

type Language = 'id' | 'jp' | 'en';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  id: {
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.menu': 'Menu',
    'nav.gallery': 'Galeri',
    'nav.reviews': 'Ulasan',
    'nav.contact': 'Kontak',
    'hero.headline': 'SAMA-SAMA',
    'hero.subheadline': 'Rasa Indonesia Asli di Tengah Nagoya',
    'hero.description': 'Nikmati masakan halal khas Indonesia dengan cita rasa rumahan yang autentik.',
    'hero.cta.menu': 'Lihat Menu',
    'hero.cta.reserve': 'Reservasi',
    'about.title': 'Cerita Kami',
    'about.subtitle': 'Tentang SAMA-SAMA',
    'about.p1': 'SAMA-SAMA hadir untuk membawa cita rasa Indonesia yang autentik ke Jepang. Kami percaya bahwa makanan adalah jembaga yang menghubungkan budaya dan membangun persahabatan.',
    'about.p2': 'Setiap hidangan kami disiapkan dengan bahan-bahan halal berkualitas dan resep turun-temurun dari keluarga Indonesia. Suasana hangat restoran kami dirancang untuk membuat Anda merasa seperti makan di rumah sendiri.',
    'about.p3': 'Cocok untuk mahasiswa, pekerja Indonesia, wisatawan, dan warga Jepang yang ingin mencoba kelezatan masakan Indonesia sejati.',
    'about.stats.years': 'Tahun',
    'about.stats.dishes': 'Menu',
    'about.stats.customers': 'Pelanggan',
    'menu.title': 'Menu Unggulan',
    'menu.viewAll': 'Lihat Semua Menu',
    'menu.fullTitle': 'Menu Lengkap',
    'menu.subtitle': 'Hidangan Pilihan',
    'menu.view': 'Lihat Detail',
    'menu.currency': '¥',
    'menu.rendang.name': 'Rendang',
    'menu.rendang.desc': 'Daging sapi slow-cooked dalam santan dan rempah-rempah khas Padang',
    'menu.rendang.price': '1,200',
    'menu.nasgor.name': 'Nasi Goreng Spesial',
    'menu.nasgor.desc': 'Nasi goreng dengan udang, ayam, dan telur mata sapi',
    'menu.nasgor.price': '1,000',
    'menu.sate.name': 'Sate Ayam',
    'menu.sate.desc': 'Sate ayam bakar dengan bumbu kacang dan lontong',
    'menu.sate.price': '1,100',
    'menu.penyet.name': 'Ayam Penyet',
    'menu.penyet.desc': 'Ayam goreng penyet dengan sambal terasi dan lalapan',
    'menu.penyet.price': '1,000',
    'menu.bakso.name': 'Bakso',
    'menu.bakso.desc': 'Bakso daging sapi dengan mie, tahu, dan kuah kaldu',
    'menu.bakso.price': '900',
    'menu.mie.name': 'Mie Goreng Jawa',
    'menu.mie.desc': 'Mie goreng Jawa dengan ayam, udang, dan sayuran',
    'menu.mie.price': '950',
    'halal.title': '100% Muslim Friendly',
    'halal.subtitle': 'Halal Food Restaurant',
    'halal.p1': 'Semua bahan makanan dan proses pembuatan telah tersertifikasi halal. Kami berkomitmen untuk menyajikan hidangan yang aman dan sesuai dengan prinsip syariah.',
    'halal.p2': 'Daging sapi dan ayam berasal dari pemasok halal terpercaya. Tidak ada alkohol atau bahan non-halal dalam setiap hidangan kami.',
    'halal.badge': 'Halal Certified',
    'gallery.title': 'Galeri',
    'gallery.subtitle': 'Suasana SAMA-SAMA',
    'testimonials.title': 'Apa Kata Mereka',
    'testimonials.subtitle': 'Ulasan Pelanggan',
    'location.title': 'Lokasi',
    'location.subtitle': 'Kunjungi Kami',
    'location.address': 'Alamat',
    'location.phone': 'Telepon',
    'location.hours': 'Jam Buka',
    'location.hours.value': 'Buka setiap hari sampai pukul 22:00',
    'location.directions': 'Petunjuk Arah',
    'footer.tagline': 'Rasa Indonesia, Kenangan Bersama',
    'footer.hours': 'Jam Buka',
    'footer.contact': 'Kontak',
    'footer.navigation': 'Navigasi',
    'footer.follow': 'Ikuti Kami',
    'footer.copyright': '© 2024 SAMA-SAMA Halal Food. All rights reserved.',
  },
  jp: {
    'nav.home': 'ホーム',
    'nav.about': 'について',
    'nav.menu': 'メニュー',
    'nav.gallery': 'ギャラリー',
    'nav.reviews': 'レビュー',
    'nav.contact': 'アクセス',
    'hero.headline': 'SAMA-SAMA',
    'hero.subheadline': '名古屋の中心で本格インドネシア料理を',
    'hero.description': 'ハラール認証の伝統的なインドネシア家庭料理をお楽しみください。',
    'hero.cta.menu': 'メニューを見る',
    'hero.cta.reserve': '予約する',
    'about.title': '私たちの物語',
    'about.subtitle': 'SAMA-SAMAについて',
    'about.p1': 'SAMA-SAMAは、本場のインドネシアの味を日本に届けるために生まれました。食事は文化をつなぎ、友情を築く架け橋であると私たちは信じています。',
    'about.p2': 'すべての料理は、高品質なハラール食材とインドネシアの家族から受け継がれたレシピで調理されています。温かい雰囲気のレストランは、まるで自宅で食事をしているような気分にさせてくれます。',
    'about.p3': '留学生、インドネシア人労働者、観光客、そして本場のインドネシア料理を試してみたい日本人の皆様に最適です。',
    'about.stats.years': '年間',
    'about.stats.dishes': 'メニュー',
    'about.stats.customers': 'お客様',
    'menu.title': 'おすすめメニュー',
    'menu.viewAll': 'すべてのメニュー',
    'menu.fullTitle': 'メニュー',
    'menu.subtitle': '人気料理',
    'menu.view': '詳細を見る',
    'menu.currency': '¥',
    'menu.rendang.name': 'ルンダン',
    'menu.rendang.desc': 'パダン風スパイスとココナッツミルクでじっくり煮込んだ牛肉',
    'menu.rendang.price': '1,200',
    'menu.nasgor.name': 'ナシゴレンスペシャル',
    'menu.nasgor.desc': 'エビ、鶏肉、目玉焼きのせナシゴレン',
    'menu.nasgor.price': '1,000',
    'menu.sate.name': 'サテアヤム',
    'menu.sate.desc': 'ピーナッツソースとロントンを添えた鶏肉サテ',
    'menu.sate.price': '1,100',
    'menu.penyet.name': 'アヤムプニャット',
    'menu.penyet.desc': 'バルサンバルと野菜を添えた揚げ鶏',
    'menu.penyet.price': '1,000',
    'menu.bakso.name': 'バクソ',
    'menu.bakso.desc': '牛肉のミートボール、麺、豆腐、スープ',
    'menu.bakso.price': '900',
    'menu.mie.name': 'ミーゴレンジャワ',
    'menu.mie.desc': '鶏肉、エビ、野菜のジャワ風焼きそば',
    'menu.mie.price': '950',
    'halal.title': '100% ムスリムフレンドリー',
    'halal.subtitle': 'ハラールフードレストラン',
    'halal.p1': 'すべての食材と調理プロセスはハラール認証を受けています。シャリアの原則に準拠した安全な料理を提供することをお約束します。',
    'halal.p2': '牛肉と鶏肉は信頼できるハラールサプライヤーから調達しています。料理にはアルコールや非ハラール素材は一切使用していません。',
    'halal.badge': 'ハラール認証',
    'gallery.title': 'ギャラリー',
    'gallery.subtitle': 'SAMA-SAMAの雰囲気',
    'testimonials.title': 'お客様の声',
    'testimonials.subtitle': 'レビュー',
    'location.title': 'アクセス',
    'location.subtitle': 'お問い合わせ',
    'location.address': '住所',
    'location.phone': '電話',
    'location.hours': '営業時間',
    'location.hours.value': '毎日営業 22:00まで',
    'location.directions': '道順',
    'footer.tagline': 'インドネシアの味、共に思い出を',
    'footer.hours': '営業時間',
    'footer.contact': '連絡先',
    'footer.navigation': 'ナビゲーション',
    'footer.follow': 'フォローする',
    'footer.copyright': '© 2024 SAMA-SAMA Halal Food. All rights reserved.',
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.menu': 'Menu',
    'nav.gallery': 'Gallery',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'hero.headline': 'SAMA-SAMA',
    'hero.subheadline': 'Authentic Indonesian Taste in Nagoya',
    'hero.description': 'Enjoy authentic Indonesian home-style halal cuisine in the heart of Nagoya.',
    'hero.cta.menu': 'View Menu',
    'hero.cta.reserve': 'Reserve',
    'about.title': 'Our Story',
    'about.subtitle': 'About SAMA-SAMA',
    'about.p1': 'SAMA-SAMA was born to bring the authentic taste of Indonesia to Japan. We believe that food is a bridge that connects cultures and builds friendships.',
    'about.p2': 'Every dish is prepared with quality halal ingredients and recipes passed down from Indonesian families. Our warm atmosphere is designed to make you feel like you\'re dining at home.',
    'about.p3': 'Perfect for students, Indonesian workers, tourists, and Japanese locals who want to experience true Indonesian cuisine.',
    'about.stats.years': 'Years',
    'about.stats.dishes': 'Dishes',
    'about.stats.customers': 'Customers',
    'menu.title': 'Featured Menu',
    'menu.viewAll': 'View Full Menu',
    'menu.fullTitle': 'Full Menu',
    'menu.subtitle': 'Signature Dishes',
    'menu.view': 'View Details',
    'menu.currency': '¥',
    'menu.rendang.name': 'Rendang',
    'menu.rendang.desc': 'Slow-cooked beef in coconut milk and Padang-style spices',
    'menu.rendang.price': '1,200',
    'menu.nasgor.name': 'Special Fried Rice',
    'menu.nasgor.desc': 'Fried rice with shrimp, chicken, and sunny-side-up egg',
    'menu.nasgor.price': '1,000',
    'menu.sate.name': 'Chicken Satay',
    'menu.sate.desc': 'Grilled chicken satay with peanut sauce and rice cakes',
    'menu.sate.price': '1,100',
    'menu.penyet.name': 'Ayam Penyet',
    'menu.penyet.desc': 'Smashed fried chicken with shrimp paste chili and vegetables',
    'menu.penyet.price': '1,000',
    'menu.bakso.name': 'Bakso',
    'menu.bakso.desc': 'Beef meatballs with noodles, tofu, and savory broth',
    'menu.bakso.price': '900',
    'menu.mie.name': 'Javanese Fried Noodles',
    'menu.mie.desc': 'Javanese-style fried noodles with chicken, shrimp, and vegetables',
    'menu.mie.price': '950',
    'halal.title': '100% Muslim Friendly',
    'halal.subtitle': 'Halal Food Restaurant',
    'halal.p1': 'All ingredients and cooking processes are halal certified. We are committed to serving dishes that are safe and compliant with sharia principles.',
    'halal.p2': 'Our beef and chicken come from trusted halal suppliers. There is no alcohol or non-halal ingredients in any of our dishes.',
    'halal.badge': 'Halal Certified',
    'gallery.title': 'Gallery',
    'gallery.subtitle': 'SAMA-SAMA Atmosphere',
    'testimonials.title': 'What They Say',
    'testimonials.subtitle': 'Customer Reviews',
    'location.title': 'Location',
    'location.subtitle': 'Visit Us',
    'location.address': 'Address',
    'location.phone': 'Phone',
    'location.hours': 'Hours',
    'location.hours.value': 'Open daily until 22:00',
    'location.directions': 'Get Directions',
    'footer.tagline': 'Indonesian Flavors, Memories Together',
    'footer.hours': 'Hours',
    'footer.contact': 'Contact',
    'footer.navigation': 'Navigation',
    'footer.follow': 'Follow Us',
    'footer.copyright': '© 2024 SAMA-SAMA Halal Food. All rights reserved.',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'id',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('id');

  const t = useCallback(
    (key: string) => {
      return translations[language][key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
